spring:
  application:
    name: location_car

  # Configuration de la base de donnees
  datasource:
    url: jdbc:postgresql://localhost:5432/car_location
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver

  # Configuration de JPA/Hibernate
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuration Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: delfredtene17@gmail.com
    password: npzlkuetltimescg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Email de l'expediteur
app:
  mail:
    from: carrental@gmail.com
    fromName: Car Rental System
  base:
    url: http://localhost:8000/api

# STRIPE KEY
stripe:
  secret:
    key: STRIPE_SECRET_KEY=sk_test_51StzLk9WeRiznAYkbSHChPpWKeAJ9cVrh2mdGlHvsgtxzmXmF6fRs2BjTqMYEqGxqrRMJ4j9dJN8PHV6kTrcNkXl0094lpUYcA
    mode: test
  webhook:
    secret: whsec_44ba59e314f0bf9caaa92c0b2020fa346c158158ac0b84fa2ebc4a90a4e6aa40
  success:
    url: http://localhost:8000/api/payment/success
  cancel:
    url: http://localhost:8000/api/payment/cancel

# Configuration du serveur
server:
  servlet:
    context-path: /api
  port: 8000